# Generated by Django 5.1.1 on 2024-09-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_agent_assistant_homeowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='users.assistant'),
        ),
    ]
