# Generated by Django 5.1.1 on 2024-09-19 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_agent_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='homeowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='users.homeowner'),
        ),
    ]
