# Generated by Django 5.1.1 on 2025-02-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_newslettersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='homeowner',
        ),
        migrations.AddField(
            model_name='agent',
            name='homeowners',
            field=models.ManyToManyField(blank=True, related_name='agents', to='users.homeowner'),
        ),
    ]
