# Generated by Django 5.1.1 on 2024-09-10 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('homeowner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('agent_remarks', models.TextField(blank=True, null=True)),
                ('process', models.CharField(choices=[('%', 'Percentage'), ('&', 'And'), ('Contact Agent', 'Contact Agent'), ('Send Offer', 'Send Offer')], max_length=15)),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('square_feet', models.IntegerField()),
                ('contract', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('property_images', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('approval_status', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeowner.homeowner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
