# Generated by Django 5.1.1 on 2024-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_assistant_property_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favourites',
            field=models.BooleanField(default=False),
        ),
    ]
