# Generated by Django 5.1.1 on 2024-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='compensation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
