# Generated by Django 5.1.1 on 2025-01-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_favourites_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='compensation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
