# Generated by Django 5.1.1 on 2024-09-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_compensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
