# Generated by Django 5.1.1 on 2025-01-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='compensation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
