# Generated by Django 5.1.1 on 2024-09-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_document'),
        ('users', '0007_agent_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.assistant'),
        ),
    ]
