# Generated by Django 5.1.1 on 2024-09-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_successful',
            field=models.BooleanField(default=False),
        ),
    ]
